#!/bin/bash

chmod +w install/boot
cd install/boot
cp initrd.ubuntu initrd.gz
gunzip initrd.gz
chmod +w initrd
cp ../../assets/preseed ./preseed.cfg
echo "preseed.cfg" | cpio -o -H newc -A -F initrd
gzip initrd
mv initrd.gz initrd.ubuntu
chmod +w initrd.siz
printf "0: %08x" $(du -b initrd.ubuntu | awk '{print $1}') | xxd -r > initrd.siz
