#!/bin/bash
# generate password to inject into the zLinux install
# v0.1 script done
# v0.2 far from done. so many bugs in this little script....
# v0.3 logging still buggy... fixed it.

logit () {
    # log to file all messages
    logdate=`date "+%F-%T"`
    echo "$logdate:$1" >> ./logs/password_create.log.$logdate
}

# set up color attributes variables
red=`tput setaf 1`
green=`tput setaf 2`
yellow=`tput setaf 3`
blue=`tput setaf 4`
magenta=`tput setaf 5`
cyan=`tput setaf 6`
white=`tput setaf 7`
blink=`tput blink`
rev=`tput rev`
reset=`tput sgr0`

# now let's remove the line that has user ZUBUNTU password (it at all)
sed -i '/^d-i passwd\/user-password-crypted password/d' ./assets/preseed > /dev/null 2>&1

echo "${white}You will now be asked for a password for zLinux user zubuntu.."
# now let's inject the newly created password
until encryptedPass=`openssl passwd -6`
do
    echo "${red}Passwords not matching! Retry...${reset}"
    sleep 1
done
echo "${yellow}Encrypted password has been generated ${reset}"
sed -i "39i d-i passwd/user-password-crypted password $encryptedPass" -i ./assets/preseed
echo "${reset}"
exit
